name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest test_main.py --params-file quadsim/params/dr_vp.py
        pytest test_main.py --params-file quadsim/params/dr_vp_nodal.py
        pytest test_main.py --params-file quadsim/params/cinema_vp.py
        pytest test_main.py --params-file quadsim/params/cinema_vp_nodal.py
        pytest test_main.py --params-file quadsim/params/cinema_vp.py --plot trajectory
        pytest test_main.py --params-file quadsim/params/cinema_vp.py --plot camera_view
        pytest test_main.py --params-file quadsim/params/cinema_vp.py --plot conic_view
        pytest test_main.py --params-file quadsim/params/cinema_vp.py --plot scp_iters
        pytest test_main.py --params-file quadsim/params/cinema_vp.py --plot constr_vio
        pytest test_main.py --params-file quadsim/params/cinema_vp.py --plot control
        pytest test_main.py --params-file quadsim/params/cinema_vp.py --plot state
        pytest test_main.py --params-file quadsim/params/cinema_vp.py --plot losses
