name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py --params-file quadsim/params/dr_vp.py
        python main.py --params-file quadsim/params/dr_vp_nodal.py
        python main.py --params-file quadsim/params/cinema_vp.py
        python main.py --params-file quadsim/params/cinema_vp_nodal.py

    - name: Run tests
      run: |
        pytest
